export const projects = [
  {
    id: 1,
    title: "E-Commerce Mobile App",
    shortDescription: "Aplikasi mobile e-commerce dengan fitur lengkap untuk fashion & lifestyle products.",
    category: "Mobile Application",
    client: "Fashion Retailer Inc",
    image: "/assets/images/mobile-mockup.svg",
    technologies: ["Flutter", "Firebase", "REST API", "Stripe Payment"],
    year: "2024",
    platform: "Android & iOS",
    fullDescription: "Aplikasi e-commerce cross-platform dengan user experience yang seamless. Dilengkapi dengan fitur product catalog, shopping cart, payment gateway, order tracking, dan customer reviews.",
    features: [
      "Product catalog dengan filter & search advanced",
      "Shopping cart & wishlist management",
      "Multiple payment methods (Credit Card, E-Wallet, COD)",
      "Real-time order tracking",
      "Push notifications untuk promo & order updates",
      "Customer reviews & ratings",
      "Chat with seller feature",
      "Admin dashboard untuk inventory management"
    ],
    challenges: "Optimasi performa untuk handling 10,000+ products dan integrasi dengan multiple payment gateways.",
    results: "Aplikasi berhasil diluncurkan dengan 50K+ downloads dalam 3 bulan pertama dan rating 4.7/5.",
    link: null
  },
  {
    id: 2,
    title: "Company Profile Website",
    shortDescription: "Website company profile modern dengan CMS untuk perusahaan teknologi.",
    category: "Web Application",
    client: "Tech Solutions Ltd",
    image: "/assets/images/laptop-mockup.svg",
    technologies: ["Laravel", "MySQL", "Bootstrap", "jQuery"],
    year: "2024",
    platform: "Web",
    fullDescription: "Website company profile yang elegant dan responsive dengan content management system untuk memudahkan update konten tanpa technical knowledge.",
    features: [
      "Responsive design untuk semua device",
      "CMS untuk manage content (About, Services, Portfolio, Blog)",
      "Contact form dengan email notification",
      "SEO optimized",
      "Blog system dengan categories & tags",
      "Portfolio showcase dengan filter",
      "Multi-language support (ID & EN)",
      "Admin dashboard untuk content management"
    ],
    challenges: "Membuat CMS yang user-friendly untuk non-technical users dengan preview before publish feature.",
    results: "Website meningkatkan online presence klien dengan traffic 200% dalam 6 bulan dan lead generation meningkat 150%.",
    link: null
  },
  {
    id: 3,
    title: "Restaurant Management System",
    shortDescription: "Sistem manajemen restoran lengkap dengan POS, inventory, dan kitchen display.",
    category: "Web & Mobile App",
    client: "Restaurant Chain Group",
    image: "/assets/images/hero-illustration.svg",
    technologies: ["Laravel", "React", "Flutter", "PostgreSQL", "Redis"],
    year: "2024",
    platform: "Web & Mobile",
    fullDescription: "Sistem terintegrasi untuk mengelola operasional restoran chain dengan multiple outlets. Terdiri dari POS system, inventory management, kitchen display system, dan mobile app untuk customer ordering.",
    features: [
      "POS System dengan split bill & table management",
      "Inventory management dengan auto stock alert",
      "Kitchen Display System untuk order tracking",
      "Customer mobile app untuk pre-order & loyalty program",
      "Real-time sales reporting & analytics",
      "Multi-outlet support dengan centralized management",
      "Staff management dengan role-based access",
      "Integration dengan online delivery platforms"
    ],
    challenges: "Real-time synchronization antara POS, kitchen display, dan mobile app dengan minimal latency.",
    results: "Meningkatkan efisiensi operasional 40% dan mengurangi order error hingga 80%. Digunakan di 15 outlet restoran.",
    link: null
  },
  {
    id: 4,
    title: "Healthcare Appointment System",
    shortDescription: "Platform booking appointment rumah sakit dengan telemedicine feature.",
    category: "Web Application",
    client: "General Hospital Network",
    image: "/assets/images/professional-coding.svg",
    technologies: ["Node.js", "React", "MongoDB", "WebRTC", "Socket.io"],
    year: "2024",
    platform: "Web",
    fullDescription: "Platform digital untuk memudahkan pasien booking appointment dokter secara online, dilengkapi dengan fitur telemedicine untuk konsultasi jarak jauh.",
    features: [
      "Doctor profile & schedule management",
      "Online appointment booking dengan reminder",
      "Telemedicine video call dengan WebRTC",
      "Electronic medical records (EMR)",
      "Prescription & lab result management",
      "Payment integration untuk consultation fee",
      "Queue management system",
      "Patient history & analytics untuk dokter"
    ],
    challenges: "Keamanan data pasien (HIPAA compliance) dan stabilitas video call untuk telemedicine.",
    results: "Digunakan oleh 50+ dokter dengan 1000+ appointment per bulan. Mengurangi no-show rate hingga 60%.",
    link: null
  },
  {
    id: 5,
    title: "Learning Management System (LMS)",
    shortDescription: "Platform pembelajaran online dengan fitur course management dan live class.",
    category: "Web Application",
    client: "Education Institute",
    image: "/assets/images/learning-student.svg",
    technologies: ["Laravel", "Vue.js", "MySQL", "Jitsi Meet", "AWS S3"],
    year: "2023",
    platform: "Web",
    fullDescription: "Platform e-learning lengkap untuk institusi pendidikan dengan fitur course management, video learning, quiz, dan live class.",
    features: [
      "Course creation & content management",
      "Video upload & streaming dengan adaptive bitrate",
      "Quiz & assignment dengan auto-grading",
      "Live class dengan video conferencing",
      "Discussion forum untuk setiap course",
      "Progress tracking & certification",
      "Grade book & analytics untuk instructor",
      "Mobile-responsive interface"
    ],
    challenges: "Video streaming optimization untuk connection yang bervariasi dan scalability untuk concurrent live sessions.",
    results: "Platform digunakan oleh 500+ students dan 30+ instructors dengan satisfaction rate 4.5/5.",
    link: null
  },
  {
    id: 6,
    title: "Real Estate Marketplace",
    shortDescription: "Platform jual-beli properti dengan virtual tour dan mortgage calculator.",
    category: "Web Application",
    client: "Property Agency Network",
    image: "/assets/images/hero-illustration.svg",
    technologies: ["Laravel", "React", "PostgreSQL", "Google Maps API", "Matterport"],
    year: "2023",
    platform: "Web",
    fullDescription: "Marketplace properti modern dengan fitur pencarian advanced, virtual tour 360°, dan mortgage calculator untuk memudahkan pembeli dalam decision making.",
    features: [
      "Property listing dengan advanced filters",
      "Virtual tour 360° untuk property showcase",
      "Interactive map dengan location-based search",
      "Mortgage calculator & financing simulation",
      "Direct messaging antara buyer & agent",
      "Save favorite properties & comparison feature",
      "Agent dashboard untuk property management",
      "Lead management & analytics untuk agency"
    ],
    challenges: "Integration dengan Matterport untuk virtual tour dan optimasi map performance dengan ribuan markers.",
    results: "1000+ property listings dengan 100K+ monthly visitors. Conversion rate meningkat 35% dengan virtual tour feature.",
    link: null
  },
  {
    id: 7,
    title: "Fintech Mobile App",
    shortDescription: "Aplikasi financial technology untuk digital payment dan peer-to-peer lending.",
    category: "Mobile Application",
    client: "FinTech Startup",
    image: "/assets/images/mobile-mockup.svg",
    technologies: ["Kotlin", "Jetpack Compose", "Firebase", "Xendit API", "Retrofit"],
    year: "2023",
    platform: "Android",
    fullDescription: "Aplikasi fintech yang menyediakan layanan digital payment, transfer antar bank, QRIS payment, dan peer-to-peer lending dengan credit scoring system.",
    features: [
      "Digital wallet & top-up balance",
      "Transfer antar bank real-time",
      "QRIS payment untuk merchant",
      "Bill payment (listrik, air, pulsa, dll)",
      "Peer-to-peer lending dengan AI credit scoring",
      "Investment portfolio untuk mutual funds",
      "Transaction history & financial reports",
      "Biometric authentication (fingerprint & face ID)"
    ],
    challenges: "Security implementation untuk financial transactions dan compliance dengan OJK regulations.",
    results: "100K+ registered users dengan transaction volume Rp 10M+ per bulan. Security audit passed dengan A rating.",
    link: null
  },
  {
    id: 8,
    title: "Inventory Management System",
    shortDescription: "Sistem manajemen inventory & warehouse dengan barcode scanning.",
    category: "Web & Mobile App",
    client: "Manufacturing Company",
    image: "/assets/images/laptop-mockup.svg",
    technologies: ["Laravel", "Flutter", "PostgreSQL", "Redis", "Zebra SDK"],
    year: "2023",
    platform: "Web & Mobile",
    fullDescription: "Sistem inventory management terintegrasi untuk manufactur dengan multi-warehouse support, barcode scanning, dan real-time stock tracking.",
    features: [
      "Multi-warehouse inventory management",
      "Barcode & QR code scanning untuk stock in/out",
      "Real-time stock level monitoring",
      "Auto purchase order generation",
      "Supplier management & procurement",
      "Batch & serial number tracking",
      "Stock opname & cycle counting",
      "Inventory reports & analytics dashboard"
    ],
    challenges: "Real-time synchronization untuk multi-warehouse dan integration dengan existing ERP system.",
    results: "Mengurangi stock discrepancy hingga 90% dan meningkatkan inventory turnover ratio 25%.",
    link: null
  }
];
